package com.yd.picmaker.model;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.yd.picmaker.model.StickerSaveData;

import com.yd.picmaker.model.StickerSaveDataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig stickerSaveDataDaoConfig;

    private final StickerSaveDataDao stickerSaveDataDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        stickerSaveDataDaoConfig = daoConfigMap.get(StickerSaveDataDao.class).clone();
        stickerSaveDataDaoConfig.initIdentityScope(type);

        stickerSaveDataDao = new StickerSaveDataDao(stickerSaveDataDaoConfig, this);

        registerDao(StickerSaveData.class, stickerSaveDataDao);
    }
    
    public void clear() {
        stickerSaveDataDaoConfig.clearIdentityScope();
    }

    public StickerSaveDataDao getStickerSaveDataDao() {
        return stickerSaveDataDao;
    }

}
